/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.cloudogu.smp

import org.gradle.api.GradleException
import org.gradle.api.JavaVersion
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.plugins.JavaLibraryPlugin
import org.gradle.api.publish.maven.plugins.MavenPublishPlugin
import org.gradle.api.tasks.compile.JavaCompile

class GradleSmpPlugin implements Plugin<Project> {

  void apply(Project project) {
    if (!project.version?.trim() || "unspecified".equals(project.version) ) {
      throw new GradleException("version is missing in gradle.properties")
    }

    project.plugins.apply(JavaLibraryPlugin)
    project.plugins.apply("io.swagger.core.v3.swagger-gradle-plugin")
    project.plugins.apply(MavenPublishPlugin)

    project.tasks.withType(JavaCompile) {
      sourceCompatibility = JavaVersion.VERSION_1_8
      targetCompatibility = JavaVersion.VERSION_1_8
    }

    def packageJson = new PackageJson(project)
    def extension = project.extensions.create("scmPlugin", SmpExtension)

    DoctorTasks.configure(project, extension, packageJson)
    LicenseTasks.configure(project)
    Dependencies.configure(project, extension)
    UiTasks.configure(project, packageJson)
    TestTasks.configure(project)

    def artifact = PackagingTasks.configure(project, packageJson, extension)
    PublishingTasks.configure(project, extension, artifact)
    RunTasks.configure(project, packageJson, extension)
    VersionTasks.configure(project)
  }

}
