/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.cloudogu.smp

import org.gradle.api.GradleException
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.plugins.JavaLibraryPlugin
import org.gradle.api.publish.maven.plugins.MavenPublishPlugin
import org.gradle.api.tasks.compile.JavaCompile
import org.gradle.jvm.toolchain.JavaLanguageVersion

class GradleSmpPlugin implements Plugin<Project> {

  void apply(Project project) {
    if (!project.version?.trim() || "unspecified".equals(project.version) ) {
      throw new GradleException("version is missing in gradle.properties")
    }

    project.plugins.apply(JavaLibraryPlugin)
    project.plugins.apply(MavenPublishPlugin)
    project.plugins.apply(com.cloudogu.changelog.GradlePlugin)

    def extension = project.extensions.create("scmPlugin", SmpExtension, project)
    def jvmVersion = extension.scmVersion.map(v -> v.equals("2.29.0") ? 8 : 11)

    project.java {
      toolchain {
        languageVersion = JavaLanguageVersion.of(11)
      }
    }

    project.tasks.withType(JavaCompile) {
      options.release = jvmVersion
      options.encoding = 'UTF-8'
    }

    def packageJson = new PackageJson(project)

    AnalysisTasks.configure(project, extension, packageJson)
    DoctorTasks.configure(project, extension, packageJson)
    LicenseTasks.configure(project)
    Dependencies.configure(project, extension)
    UiTasks.configure(project, packageJson)
    TestTasks.configure(project)

    def artifact = PackagingTasks.configure(project, packageJson, extension)
    PublishingTasks.configure(project, extension, artifact)
    RunTasks.configure(project, packageJson, extension)
    VersionTasks.configure(project, extension)
  }

}
